name: z0und
description: Zound Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.0.1
  google_fonts: ^3.0.1
  id3: ^1.0.2
  just_audio: ^0.9.30
  path: ^1.8.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/sample-audio-track.mp3
